=== fenix23707/epam-tasks/task03/src/main/resources/candies.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.by/task03/candies"
    xmlns:tns="http://www.epam.by/task03/candies" elementFormDefault="qualified">

    <element name="candies">

        <complexType>
            <sequence>
                <element name="candy" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="energy" type="nonNegativeInteger"/>
                            <element name="type" type="tns:candyType"/>
                            <element name="ingredients" type="tns:ingredientsType"/>
                            <element name="value" type="tns:valueType"/>
                            <element name="production" type="string"/>
                        </sequence>
                        <attribute name="id" type="string" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

    <simpleType name="candyType">
        <restriction base="string">
            <enumeration value="CARAMEL"/>
            <enumeration value="IRIS"/>
            <enumeration value="CHOCOLATE"/>
        </restriction>
    </simpleType>

    <complexType name="valueType">
        <attribute name="protein" type="tns:limitedFloat" use="required"/>
        <attribute name="fats" type="tns:limitedFloat" use="required"/>
        <attribute name="carbohydrates" type="tns:limitedFloat" use="required"/>
    </complexType>

    <complexType name="ingredientsType">
        <all>
            <element name="water" type="tns:limitedFloat"/>
            <element name="sugar" type="tns:limitedFloat"/>
            <element name="fructose" type="tns:limitedFloat"/>
            <element name="chocolateType" type="string" minOccurs="0"/>
            <element name="vanillin" type="tns:limitedFloat"/>
        </all>
    </complexType>
    
    <simpleType name="limitedFloat">
        <restriction base="float">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>

</schema>

=== fenix23707/epam-tasks/task03/src/main/resources/newCandies.xml
<?xml version="1.0" encoding="UTF-8"?><candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.epam.by/task03/candies" xsi:schemaLocation="http://www.epam.by/task03/candies candies.xsd"><candy id="3"><name>Bob Snail</name><energy>132</energy><type>CARAMEL</type><ingredients><vanillin>7.8</vanillin><water>3.1</water><sugar>1.3</sugar><fructose>6.3</fructose></ingredients><value protein="1.2" fats="1.0" carbohydrates="29.6"></value><production>Bob Snail</production></candy><candy id="2"><name>Аленка</name><energy>550</energy><type>IRIS</type><ingredients><vanillin>3</vanillin><fructose>6.1</fructose><water>3.2</water><sugar>1.2</sugar></ingredients><value protein="6.0" fats="33.0" carbohydrates="56.0"></value><production>Spartak</production></candy><candy id="1"><name>truffle</name><energy>564</energy><type>CHOCOLATE</type><ingredients><fructose>0</fructose><sugar>0</sugar><water>4.9</water><chocolateType>bitter</chocolateType><vanillin>0</vanillin></ingredients><value protein="4.9" fats="38.1" carbohydrates="50.3"></value><production>Sorceress</production></candy></candies>

=== fenix23707/epam-tasks/task03/src/main/resources/candies.xml
<?xml version="1.0" encoding="UTF-8" ?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.epam.by/task03/candies" xsi:schemaLocation="http://www.epam.by/task03/candies candies.xsd">
1;truffle;564;CHOCOLATE;4.9
    <candy id="1">
        <name>truffle</name>
        <energy>564</energy>
        <type>CHOCOLATE</type>
        <ingredients>
            <water>4.9</water>
            <sugar>0</sugar>
            <fructose>0</fructose>
            <chocolateType>bitter</chocolateType>
            <vanillin>0</vanillin>
        </ingredients>
        <value protein="4.9" fats="38.1" carbohydrates="50.3"/>
        <production>Sorceress</production>
    </candy>

    <candy id="2">
        <name>Аленка</name>
        <energy>550</energy>
        <type>IRIS</type>
        <ingredients>
            <water>3.2</water>
            <sugar>1.2</sugar>
            <fructose>6.1</fructose>
            <vanillin>3</vanillin>
        </ingredients>
        <value protein="6.0" fats="33" carbohydrates="56"/>
        <production>Spartak</production>
    </candy>

   <candy id="3">
       <name>Bob Snail</name>
       <energy>132</energy>
       <type>CARAMEL</type>
       <ingredients>
           <water>3.1</water>
           <sugar>1.3</sugar>
           <fructose>6.3</fructose>
           <vanillin>7.8</vanillin>
       </ingredients>
       <value protein="1.2" fats="1.0" carbohydrates="29.6"/>
       <production>Bob Snail</production>
   </candy>

</candies>
